arb-dir: lib/l10n
output-dir: lib/l10n/generate

template-arb-file: app_vi.arb

output-class: AppLocalizations
output-localization-file: app_localizations.dart

synthetic-package: false
nullable-getter: false