// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOlH7UATxpQkECzOY6-sXdBIbp_mVCaVg',
    appId: '1:725041116937:web:9997482cec8716001dc5d8',
    messagingSenderId: '725041116937',
    projectId: 'vinhmdev',
    authDomain: 'vinhmdev.firebaseapp.com',
    storageBucket: 'vinhmdev.appspot.com',
    measurementId: 'G-TGL9KC57S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_4aAx7HRBiXLX5gee-JxsC-zj5mNrsII',
    appId: '1:725041116937:android:1a55d61f2104a4381dc5d8',
    messagingSenderId: '725041116937',
    projectId: 'vinhmdev',
    storageBucket: 'vinhmdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD0SjMMZ-TkLK966G4sufho1Id1fNDbCM',
    appId: '1:725041116937:ios:81737008ef11db481dc5d8',
    messagingSenderId: '725041116937',
    projectId: 'vinhmdev',
    storageBucket: 'vinhmdev.appspot.com',
    iosClientId: '725041116937-goaoin4v32c3oh2djr9i504uu8gokjca.apps.googleusercontent.com',
    iosBundleId: 'com.example.vinhmdev',
  );
}
